namespace WinUI.DependencyInjection;

partial class Templates
{
    public class XamlMetadataServiceProviderAttribute
    {
        public const string Name = nameof(XamlMetadataServiceProviderAttribute);
        public const string FullName = $"{Namespace}.{Name}";
        public static string Text { get; } =  $$"""
// <auto-generated>

namespace {{Namespace}}
{
    ///<summary>
    /// Generates a custom XamlMetadataProvider for the attributed class (App), which supports Microsoft.UI.Xaml.Controls.Page activation via a service provider.
    /// </summary>
    /// <remarks>
    /// The class must have a Microsoft.Extensions.Hosting.IHost property named 'Host' and a XamlMetaDataProvider named '_AppProvider' property.
    /// If this is not possible, implement the IXamlMetadataServiceProvider interface. The default XamlMetadataProvider is generated by the
    /// XamlCompiler (CSharpTypeInfoPass2.tt). The App implicitly implements the Microsoft.UI.Xaml.Markup.IXamlMetadataProvider interface.
    /// If this changes and the implementation becomes explicit, it will break this functionality.
    /// </remarks>
	{{GeneratedCodeAttribute}}
    [global::System.AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class {{Name}} : global::System.Attribute
    {
    }
}

""";
    }
}
