// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WinUI.DependencyInjection
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class XamlMetadataServiceProviderCodeGenerator : CodeGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n\r\nnamespace ");
            
            #line 5 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AppMetadataProviderNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class ");
            
            #line 7 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 7 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider\r\n    {\r\n        ");
            
            #line 9 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        private ");
            
            #line 10 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider __diXamlMetadataProvider;\r\n\r\n        ");
            
            #line 12 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 13 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.DebuggerNonUserCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        private ");
            
            #line 14 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider _DiXamlMetadataProvider => __diXamlMetadataProvider ??= ne" +
                    "w global::");
            
            #line 14 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.XamlTypeInfoNamespace));
            
            #line default
            #line hidden
            this.Write(".XamlMetadataServiceProvider(this);\r\n        \r\n        ");
            
            #line 16 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 17 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.DebuggerNonUserCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 18 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType ");
            
            #line 18 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider.GetXamlType(global::System.Type type) => _DiXamlMetadataPr" +
                    "ovider.GetXamlType(type);\r\n        \r\n        ");
            
            #line 20 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 21 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.DebuggerNonUserCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 22 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType ");
            
            #line 22 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider.GetXamlType(string fullName) => _DiXamlMetadataProvider.Ge" +
                    "tXamlType(fullName);\r\n        \r\n        ");
            
            #line 24 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 25 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.DebuggerNonUserCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 26 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".XmlnsDefinition[] ");
            
            #line 26 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider.GetXmlnsDefinitions() => _DiXamlMetadataProvider.GetXmlnsD" +
                    "efinitions();\r\n    }\r\n}\r\n\r\nnamespace ");
            
            #line 30 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.XamlTypeInfoNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    ");
            
            #line 32 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 33 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.DebuggerNonUserCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 34 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Visibility));
            
            #line default
            #line hidden
            this.Write(" sealed class XamlMetadataServiceProvider : ");
            
            #line 34 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider\r\n    {\r\n        private global::");
            
            #line 36 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HasServiceProviderInterface ? Templates.IXamlMetadataServiceProvider.FullName : Model.ClassFullName));
            
            #line default
            #line hidden
            this.Write(" App { get; }\r\n        private ");
            
            #line 37 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider AppProvider { get; }\r\n\r\n        public XamlMetadataService" +
                    "Provider(global::");
            
            #line 39 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HasServiceProviderInterface ? Templates.IXamlMetadataServiceProvider.FullName : Model.ClassFullName));
            
            #line default
            #line hidden
            this.Write(@" app)
        {
            // Note: I think this implementation resolved the issue because now only pages can be instantiated by a service provider, and the IServiceProviderIsService is not used in this case.

            // Do not initialize IsService/services here, as they may not be available yet.

            // I used a ScrollView/RTB (or I'd say, a UI element) to display logs. Any UI element is instantiated via the custom XamlMetadataProvider.
            // The custom XamlMetadataProvider checks whether the underlying type is a registered service. When the Host is built, it logs its creation.
            // If a logger uses any UI element, the custom XamlMetadataProvider will activate it, but at this point, the App's Host property isn't assigned.
            // Therefore, the custom XamlMetadataProvider cannot use the IsService property; otherwise, a NullReferenceException will be thrown.
            // If the UI element's IXamlType (retrieved by the default XamlMetadataProvider.GetXamlType) isn't a XamlUserType, no issues will occur.
            // If the IXamlType is a XamlUserType, the custom XamlMetadataProvider cannot resolve it, leading to a NullReferenceException.
            // In this special case, it's recommended to instantiate any UI element lazily or after the Host is built.
            // For example, the visual logger should have a log queue, and when the App is shown, the queue should be processed.

");
            
            #line 54 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 if (Debug) { 
            
            #line default
            #line hidden
            this.Write("            global::System.Diagnostics.Debugger.Break();\r\n");
            
            #line 56 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            App = app;\r\n");
            
            #line 58 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 if (Model.IsGetAppProviderImplemented) { 
            
            #line default
            #line hidden
            this.Write("            AppProvider = app.GetAppProvider() ?? ");
            
            #line 59 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ThrowNotSupportedException_GetAppProvider));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 60 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            var propertyInfo = typeof(");
            
            #line 61 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ClassFullName));
            
            #line default
            #line hidden
            this.Write(").GetProperty(\"");
            
            #line 61 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AppProvider));
            
            #line default
            #line hidden
            this.Write("\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.Bi" +
                    "ndingFlags.Public | global::System.Reflection.BindingFlags.NonPublic) ?? ");
            
            #line 61 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ThrowNotSupportedException_GetAppProvider));
            
            #line default
            #line hidden
            this.Write(";\r\n            AppProvider = propertyInfo.GetValue(app) as ");
            
            #line 62 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMetadataProvider ?? ");
            
            #line 62 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ThrowNotSupportedException_GetAppProvider));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 63 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public object GetRequiredService(global::System.Type type) \r" +
                    "\n        {\r\n");
            
            #line 68 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 if (Model.IsGetRequiredServiceImplemented) { 
            
            #line default
            #line hidden
            this.Write("            return App.GetRequiredService(type); \r\n");
            
            #line 70 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 } else if (Model.HasHost) { 
            
            #line default
            #line hidden
            this.Write("            return global::Microsoft.Extensions.DependencyInjection.ServiceProvid" +
                    "erServiceExtensions.GetRequiredService(App.Host.Services, type);\r\n");
            
            #line 72 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
} else { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 73 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ThrowNotSupportedException_GetRequiredService));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 74 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        private bool TryGetServiceProviderXamlUserType(");
            
            #line 77 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType xamlType, out ");
            
            #line 77 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(@".IXamlType serviceProviderXamlUserType)
        {
            serviceProviderXamlUserType = null;
            // Frame.Navigate instantiates pages only, so only Microsoft.UI.Xaml.Controls.Page or its subclasses are redirected.
            if (xamlType?.UnderlyingType.IsSubclassOf(typeof(global::Microsoft.UI.Xaml.Controls.Page)) is null or false) return false;

            // The default provider caches xaml types, but pages are not instantiated too often. After some tests, I observed that GetXamlType is called only once,
            // therefore, no cahcing is implemented.
            serviceProviderXamlUserType = new ServiceProviderXamlUserType(this, xamlType);
            return true;
        }

        public ");
            
            #line 89 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(@".IXamlType GetXamlType(global::System.Type type)
        {
            var xamlType = AppProvider.GetXamlType(type);
            if (TryGetServiceProviderXamlUserType(xamlType, out var serviceProviderXamlUserType)) return serviceProviderXamlUserType;
            return xamlType;
        }

        public ");
            
            #line 96 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(@".IXamlType GetXamlType(string fullName)
        {
            var xamlType = AppProvider.GetXamlType(fullName);
            if (TryGetServiceProviderXamlUserType(xamlType, out var serviceProviderXamlUserType)) return serviceProviderXamlUserType;
            return xamlType;
        }

        public ");
            
            #line 103 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".XmlnsDefinition[] GetXmlnsDefinitions() => AppProvider.GetXmlnsDefinitions();   " +
                    "     \r\n    }\r\n\r\n    ");
            
            #line 106 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 107 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Templates.DebuggerNonUserCodeAttribute));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 108 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Visibility));
            
            #line default
            #line hidden
            this.Write(" sealed class ServiceProviderXamlUserType : ");
            
            #line 108 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType\r\n    {\r\n        public ServiceProviderXamlUserType(global::");
            
            #line 110 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.XamlTypeInfoNamespace));
            
            #line default
            #line hidden
            this.Write(".XamlMetadataServiceProvider provider, ");
            
            #line 110 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType xamlUserType)\r\n        {\r\n            Provider = provider;\r\n          " +
                    "  XamlUserType = xamlUserType;\r\n        }\r\n\r\n        public ");
            
            #line 116 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType XamlUserType { get; }\r\n        public global::");
            
            #line 117 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.XamlTypeInfoNamespace));
            
            #line default
            #line hidden
            this.Write(".XamlMetadataServiceProvider Provider { get; }\r\n        public object ActivateIns" +
                    "tance() => Provider.GetRequiredService(UnderlyingType);\r\n\r\n        public ");
            
            #line 120 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType BaseType => XamlUserType.BaseType;\r\n        public ");
            
            #line 121 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType BoxedType => XamlUserType.BoxedType;\r\n        public ");
            
            #line 122 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(@".IXamlMember ContentProperty => XamlUserType.ContentProperty;
        public string FullName => XamlUserType.FullName;
        public bool IsArray => XamlUserType.IsArray;
        public bool IsBindable => XamlUserType.IsBindable;
        public bool IsCollection => XamlUserType.IsCollection;
        public bool IsConstructible => XamlUserType.IsConstructible;
        public bool IsDictionary => XamlUserType.IsDictionary;
        public bool IsMarkupExtension => XamlUserType.IsMarkupExtension;
        public ");
            
            #line 130 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlType ItemType => XamlUserType.ItemType;\r\n        public ");
            
            #line 131 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(@".IXamlType KeyType => XamlUserType.KeyType;
        public global::System.Type UnderlyingType => XamlUserType.UnderlyingType;
        public void AddToMap(object instance, object key, object value) => XamlUserType.AddToMap(instance, key, value);
        public void AddToVector(object instance, object value) => XamlUserType.AddToVector(instance, value);
        public object CreateFromString(string value) => XamlUserType.CreateFromString(value);
        public ");
            
            #line 136 "d:\SyncRoot\Projects\VisualStudio\UI\WinUI\WinUI.DependencyInjection\WinUI.DependencyInjection\XamlMetadataServiceProviderCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MarkupNamespace));
            
            #line default
            #line hidden
            this.Write(".IXamlMember GetMember(string name) => XamlUserType.GetMember(name);\r\n        pub" +
                    "lic void RunInitializer() => XamlUserType.RunInitializer();\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
